FROM amazoncorretto:17-alpine

WORKDIR /app

ARG JAR_FILE=./build/libs/hollang-weeks52-1.0.0.jar

COPY src/main/resources/static/initData.xlsx /app/static/initData.xlsx
COPY ${JAR_FILE} hollang-weeks52-dev.jar

ENV PROFILES dev

EXPOSE 8080

ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/hollang-weeks52-dev.jar"]
