FROM amazoncorretto:17-alpine

WORKDIR /app

ARG JAR_FILE=./build/libs/hollang-weeks52-1.0.0.jar

COPY ${JAR_FILE} hollang-weeks52-stage.jar

ENV PROFILES stage

EXPOSE 80

ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/hollang-weeks52-stage.jar"]
