version: "3.8"
services:
  hollang-weeks52-api-server-prod:
    container_name: hollang-weeks52-api-server-prod
    depends_on:
      - hollang-weeks52-inferring-server-prod
    image: ${ECR_REGISTRY}/hollang-weeks52-api-server-prod:${IMAGE_TAG}
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - hollang-weeks52-network
  hollang-weeks52-inferring-server-prod:
    container_name: hollang-weeks52-inferring-server-prod
    image: ${ECR_REGISTRY}/hollang-weeks52-inferring-server-prod:latest
    restart: always
    ports:
      - "5000:5000"
    networks:
      - hollang-weeks52-network

networks:
  hollang-weeks52-network:
    driver: bridge
