version: "3.8"
services:
  hollang-weeks52-api-server-stage:
    container_name: hollang-weeks52-api-server-stage
    depends_on:
      - hollang-weeks52-inferring-server-stage
    image: ${ECR_REGISTRY}/hollang-weeks52-api-server-stage:latest
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - hollang-weeks52-network
  hollang-weeks52-inferring-server-stage:
    container_name: hollang-weeks52-inferring-server-stage
    image: ${ECR_REGISTRY}/hollang-weeks52-inferring-server-stage:latest
    restart: always
    ports:
      - "5000:5000"
    networks:
      - hollang-weeks52-network

networks:
  hollang-weeks52-network:
    driver: bridge
