server:
  port: 8081

spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hollang_test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # DB 예약어 충돌 방지
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        format_sql: true
        show_sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: h2
  h2:
    console:
      enabled: true

logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: debug
        type: trace

inferring:
  server:
    host: 127.0.0.1

client:
  server:
    host: "*"
