server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # rewriteBatchedStatements=true -> Batch Insert 옵션 ON
    url: jdbc:mysql://${MYSQL_SERVER_HOST}:3306/hollang_dev?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=1000
    username: root
    password: 11111111
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    swyg.hollang: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
