spring:
  config:
    activate:
      on-profile: prod, dev, local, test
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          # Batch Insert를 위해서 Batch Size 50으로 설정
          batch_size: 50
  mvc:
    throw-exception-if-no-handler-found: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

inferring:
  server:
    host: ${INFERRING_SERVER_HOST}

client:
  server:
    host: ${CLIENT_SERVER_HOST}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
